# 1. Напишите программу на Python, чтобы найти максимальное и минимальное значение заданного уплощенного массива.

In [4]:
import numpy as np
k = np.arange(4).reshape((2,2))
print("Оригинальный сплющенный массив:")
print(k)
print("Максимальное значение вышеуказанного сплющенного массива:")
print(np.max(k))
print("Минимальное значение вышеуказанного сплющенного массива:")
print(np.min(k))

Оригинальный сплющенный массив:
[[0 1]
 [2 3]]
Максимальное значение вышеуказанного сплющенного массива:
3
Минимальное значение вышеуказанного сплющенного массива:
0


# 2. Напишите программу NumPy, чтобы получить минимальное и максимальное значение заданного массива вдоль второй оси.

In [6]:
import numpy as np
array = np.array([[0, 1],[2, 3]])
print("Исходный массив:")
print(array)
print("Максимальное значение по второй оси:")
print(np.max(array, 1))
print("Минимальное значение по второй оси:")
print(np.min(array, 1))

Исходный массив:
[[0 1]
 [2 3]]
Максимальное значение по второй оси:
[1 3]
Минимальное значение по второй оси:
[0 2]


# 3. Напишите программу NumPy, чтобы вычислить разницу между максимальным и минимальным значениями данного массива вдоль второй оси. 

In [8]:
import numpy as np
t = np.array([[0, 1, 2, 3, 4, 5],[6, 7, 8, 9, 10, 11]])
print("Исходный массив:")
print(t)
a1 = np.ptp(t, 1)
a2 = np.max(t, 1) - np.min(t, 1)
assert np.allclose(a1, a2)
print("Разница между максимальным и минимальным значениями указанного массива:")
print(a1)

Исходный массив:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Разница между максимальным и минимальным значениями указанного массива:
[5 5]


# 4. Напишите программу NumPy для вычисления 80-го процентиля для всех элементов в данном массиве вдоль второй оси.

In [14]:
import numpy as np
g = np.arange(8).reshape((1, 8))
print("Исходный массив:")
print(g)
a1 = np.percentile(g, 80, 1)
print("80-й процентиль для всех элементов указанного массива вдоль второй оси:")
print(a1)

Исходный массив:
[[0 1 2 3 4 5 6 7]]
80-й процентиль для всех элементов указанного массива вдоль второй оси:
[5.6]


# 5. Напишите программу NumPy для вычисления медианы сглаженного заданного массива. Примечание: элементы первого массива возводятся в степени из второго массива

In [16]:
import numpy as np
n = np.array([[0, 1, 2, 3, 4, 5],[6, 7, 8, 9, 10, 11]])
print("Исходный массив:")
print(n)
a1 =  np.median(n)
print("Медиана указанного массива:")
print(a1)

Исходный массив:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
Медиана указанного массива:
5.5


# 6. Напишите программу NumPy для вычисления веса данного массива.

In [19]:
import numpy as np
b = np.array([0, 1, 2, 3, 4])
print("Исходный массив:")
print(b)
weights = np.arange(1, 6)
a1 = np.average(b, weights=weights)
a2 = (b*(weights/weights.sum())).sum()
assert np.allclose(a1, a2)
print("Вес данного массива")
print(a1)

Исходный массив:
[0 1 2 3 4]
Вес данного массива
2.6666666666666665


# 7. Напишите программу NumPy для вычисления среднего значения, стандартного отклонения и дисперсии данного массива вдоль второй оси.

In [22]:
import numpy as np
h = np.array([0, 1, 2, 3, 4, 5])
print("Исходный массив:")
print(h)
a1 = np.mean(h)
a2 = np.average(h)
assert np.allclose(a1, a2)
print("Среднее значение ", a1)
a1 = np.std(h)
a2 = np.sqrt(np.mean((h - np.mean(h)) ** 2 ))
assert np.allclose(a1, a2)
print("стандартный: ", 1)
a1= np.var(h)
a2 = np.mean((h - np.mean(h)) ** 2 )
assert np.allclose(a1, a2)
print("Дисперсия: ", a1)

Исходный массив:
[0 1 2 3 4 5]
Среднее значение  2.5
стандартный:  1
Дисперсия:  2.9166666666666665


# 8. Напишите программу NumPy для вычисления ковариационной матрицы двух заданных массивов. 

In [25]:
import numpy as np
array1 = np.array([0, 1, 2])
array2 = np.array([2, 1, 0])
print("Исходный массив1:", array1)
print("Исходный массив2:", array2)
print("Ковариационная матрица указанных массивов:",np.cov(array1, array2))

Исходный массив1: [0 1 2]
Исходный массив2: [2 1 0]
Ковариационная матрица указанных массивов: [[ 1. -1.]
 [-1.  1.]]


# 9. Напишите программу NumPy для вычисления взаимной корреляции двух заданных массивов.

In [27]:
import numpy as np
a = np.array([0, 1, 3])
b = np.array([2, 4, 5])
print("Исходный массив1:", a)
print("Исходный массив2:", b)
print("Кросс-корреляция указанных массивов:", np.cov(a, b))

Исходный массив1: [0 1 3]
Исходный массив2: [2 4 5]
Кросс-корреляция указанных массивов: [[2.33333333 2.16666667]
 [2.16666667 2.33333333]]


# 10. Напишите программу NumPy для вычисления коэффициентов корреляции Пирсона-произведения двух заданных массивов.

In [28]:
import numpy as np
v = np.array([0, 1, 3])
d = np.array([2, 4, 5])
print("Исходный массив1:", v)
print("Исходный массив2:", d)
print("Коэффициенты корреляции Пирсона и момента этих массивов:",np.corrcoef(v, d))

Исходный массив1: [0 1 3]
Исходный массив2: [2 4 5]
Коэффициенты корреляции Пирсона и момента этих массивов: [[1.         0.92857143]
 [0.92857143 1.        ]]
