# 9. Напишите программу NumPy, чтобы добавить границу (заполненную нулями) вокруг существующего массива.

In [4]:
import numpy as np
k = np.ones((3,3))
print(k)
print("1 на границе и 0 внутри в массиве ")
k = np.pad(k, pad_width=1, mode='constant', constant_values=0)
print(k)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1 на границе и 0 внутри в массиве 
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 11. Напишите программу NumPy для преобразования списка и кортежа в массивы.

In [7]:
import numpy as np
list = [1, 2, 3, 4, 5, 6, 7, 8]
print("Список в массив:")
print(np.asarray(list))
corteg = [[8, 4, 6],[1, 2, 3]]
print("Кортеж в массив:")
print(np.asarray(corteg))

Список в массив:
[1 2 3 4 5 6 7 8]
Кортеж в массив:
[[8 4 6]
 [1 2 3]]


# 13. Напишите программу NumPy для создания пустого и полного массива.

In [9]:
import numpy as np
#Создание пустого массива
t = np.empty((3,4))
print(t)
#Создание полного массива 
k = np.full((3,3),6)
print(k)

[[1.19856495e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.19680563e-311 2.63223423e-052 1.24502537e-047 1.57353424e-076]
 [1.04117924e-071 1.51073040e+160 5.22212289e-037 5.49724813e+170]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


# 15. Напишите программу NumPy, чтобы найти действительные и мнимые части массива комплексных чисел.

In [11]:
import numpy as np
wer = np.sqrt([1+0j])
pop = np.sqrt([0+1j])
print(wer)
print(pop)
print("Реальная часть массива:")
print(wer.real)
print(pop.real)
print("Мнимая часть массива:")
print(wer.imag)
print(pop.imag)

[1.+0.j]
[0.70710678+0.70710678j]
Реальная часть массива:
[1.]
[0.70710678]
Мнимая часть массива:
[0.]
[0.70710678]


# 17. Напишите программу NumPy, чтобы проверить, присутствует ли каждый элемент одномерного массива во втором массиве.

In [17]:
import numpy as np
Array1 = np.array([0, 10, 20, 40, 60])
print(Array1)
Array2 = np.array([0, 40])
print(Array2)
print("Сравните каждый элемент Array1 и Array2")
print(np.in1d(Array1, Array2))

[ 0 10 20 40 60]
[ 0 40]
Сравните каждый элемент Array1 и Array2
[ True False False  True False]


# 19. Напишите программу NumPy, чтобы получить уникальные элементы массива. 

In [19]:
import numpy as np
array = np.array([10, 10, 20, 20, 30, 30])
print(array)
print("Уникальные элементы вышеуказанного массива:")
print(np.unique(array))
wer1 = np.array([[1, 1],[2, 3]])
print(wer1)
print("Уникальные элементы вышеуказанного массива:")
print(np.unique(wer1))

[10 10 20 20 30 30]
Уникальные элементы вышеуказанного массива:
[10 20 30]
[[1 1]
 [2 3]]
Уникальные элементы вышеуказанного массива:
[1 2 3]


# 21. Напишите программу NumPy, чтобы найти набор исключений или двух массивов. Set exclusive-or вернет отсортированные, уникальные значения, которые находятся только в одном (а не в обоих) входных массивах.

In [24]:
import numpy as np
Array1 = np.array([0,10, 20, 40, 60, 80])
Array2 = np.array([10, 30, 40, 50, 70])
print(Array1)
print(Array2)
print("Уникальные значения, которые есть только в одном (а не в обоих) входных массивах:")
print(np.setxor1d(Array1, Array2))

[ 0 10 20 40 60 80]
[10 30 40 50 70]
Уникальные значения, которые есть только в одном (а не в обоих) входных массивах:
[ 0 20 30 50 60 70 80]


# 23. Напишите программу NumPy, чтобы проверить, все ли элементы массива имеют значение True. Примечание: 0 оценивается как False в NumPy.

In [26]:
import numpy as np
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([67, 20, 0, -232]))
print(np.all([90, 20, -232]))

False
True
False
True


# 25. Напишите программу NumPy для построения массива путем повторения. 

In [28]:
import numpy as np
y = np.array([1, 2, 3, 4])
print("Оригинальный массив")
print(y)
print("Повторяя 2 раза")
h = np.tile(y, 2)
print(h)
print("Повторяя 3 раза ")
h = np.tile(y, 3)
print(h)

Оригинальный массив
[1 2 3 4]
Повторяя 2 раза
[1 2 3 4 1 2 3 4]
Повторяя 3 раза 
[1 2 3 4 1 2 3 4 1 2 3 4]


# 27. Напишите программу NumPy, чтобы найти индексы максимальных и минимальных значений вдоль заданной оси массива.

In [29]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6])
print(array)
print("Максимальные значения:", np.argmax(array))
print("Минимальные значения:", np.argmin(array))

[1 2 3 4 5 6]
Максимальные значения: 5
Минимальные значения: 0
