# 1. Напишите программу NumPy для сортировки заданного массива формы 2 вдоль первой оси, последней оси и на плоском массиве.


In [2]:
import numpy as np
g = np.array([[10, 40],[30, 20]])
print(g)
print("Отсортируйте массив по первой оси:")
print(np.sort(g, axis=0))
print("Отсортируйте массив по последней оси:")
print(np.sort(g))
print("Сортировать уплощенный массив:")
print(np.sort(g, axis=None))

[[10 40]
 [30 20]]
Отсортируйте массив по первой оси:
[[10 20]
 [30 40]]
Отсортируйте массив по последней оси:
[[10 40]
 [20 30]]
Сортировать уплощенный массив:
[10 20 30 40]


# 2. Напишите программу NumPy для создания структурированного массива из заданного имени ученика, роста, класса и их типов данных. Теперь рассортируйте массив по высоте.

In [11]:
import numpy as np
a = [('name', 'S15'), ('class', int), ('height', float)]
fer = [(b'James ', 5, 48.5),(b'Nail', 6, 52.5),(b'Paul ', 5, 42.1),(b'Pit ', 5, 40.11)]
h = np.array(fer, dtype=a)                
print(h)
print("Сортировать по высоте")
print(np.sort(h, order='height'))  

[(b'James ', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul ', 5, 42.1 )
 (b'Pit ', 5, 40.11)]
Сортировать по высоте
[(b'Pit ', 5, 40.11) (b'Paul ', 5, 42.1 ) (b'James ', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


# 3. Напишите программу NumPy для создания структурированного массива из заданного имени ученика, роста, класса и их типов данных. Теперь сортируйте по классу, затем по высоте, если класс равен.

In [13]:
import numpy as np
a = [('name', 'S15'), ('class', int), ('height', float)]
fer = [(b'James ', 5, 48.5),(b'Nail', 6, 52.5),(b'Paul ', 5, 42.1),(b'Pit ', 5, 40.11)]
h = np.array(fer, dtype=a)                
print(h)
print("Сортировка по классу, затем высота, если класс равен:")
print(np.sort(h, order=['class', 'height']))

[(b'James ', 5, 48.5 ) (b'Nail', 6, 52.5 ) (b'Paul ', 5, 42.1 )
 (b'Pit ', 5, 40.11)]
Сортировка по классу, затем высота, если класс равен:
[(b'Pit ', 5, 40.11) (b'Paul ', 5, 42.1 ) (b'James ', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


# 4. Напишите программу NumPy для сортировки идентификатора ученика с ростом роста ученика по заданному идентификатору ученика и росту. Выведите целочисленные индексы, которые описывают порядок сортировки по нескольким столбцам и отсортированным данным. 

In [19]:
import numpy as np
student_id = np.array([345, 123, 67, 789, 367, 345, 700])
student_height = np.array([50., 52., 55., 51., 88., 20., 32.0])
index = np.lexsort((student_id, student_height))
print("Сортированные индексы:")
print(index)
print("Сортированные данные:")
for n in index:
  print(student_id[n], student_height[n])

Сортированные индексы:
[5 6 0 3 1 2 4]
Сортированные данные:
345 20.0
700 32.0
345 50.0
789 51.0
123 52.0
67 55.0
367 88.0


# 5. Напишите программу NumPy, чтобы получить индексы отсортированных элементов данного массива.

In [20]:
import numpy as np
j = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
print(j)
u = np.argsort(j)
print("Индексы отсортированных элементов данного массива:")
print(u)

[1023 5202 6230 1671 1682 5241 4532]
Индексы отсортированных элементов данного массива:
[0 3 4 6 1 5 2]
