# 1. Напишите программу NumPy для вычисления умножения двух заданных матриц.

In [8]:
import numpy as np
array1 = [[3, 4],[2, 9]]
array2 = [[3, 4],[1, 2]]
res1 = np.dot(array1, array2)
print("умножения двух заданных матриц")
print(res1)

умножения двух заданных матриц
[[13 20]
 [15 26]]


# 3. Напишите программу NumPy для вычисления перекрестного произведения двух заданных векторов. 

In [10]:
import numpy as np
array1 = [[3, 4],[2, 9]]
array2 = [[3, 4],[1, 2]]
res1 = np.cross(array1, array2)
res2 = np.cross(array2, array1)
print("произведение двух указанных векторов (array1, array2):")
print(res1)
print("произведение двух указанных векторов (array2, array1):")
print(res2)

произведение двух указанных векторов (array1, array2):
[ 0 -5]
произведение двух указанных векторов (array2, array1):
[0 5]


# 7. Напишите программу NumPy для вычисления собственных значений и правых собственных векторов данного квадратного массива.

In [12]:
import numpy as np
g = np.mat("2 -7;9 0")
print("a\n", g)
q, v = np.linalg.eig(g) 
print( "Собственные значения указанной матрицы",q)
print( "Собственные векторы указанной матрицы",v)

a
 [[ 2 -7]
 [ 9  0]]
Собственные значения указанной матрицы [1.+7.87400787j 1.-7.87400787j]
Собственные векторы указанной матрицы [[0.08333333+0.65616732j 0.08333333-0.65616732j]
 [0.75      +0.j         0.75      -0.j        ]]


# 8. Напишите программу NumPy для вычисления произведения Кронекера из двух заданных многомерных массивов.

In [20]:
import numpy as np
f = np.array([1,3,9])
w = np.array([2,1,0])
print(f)
print(w)
res =  np.kron(f, w)
print("Произведение Кронекера из указанных массивов:")
print(res)
j = np.arange(9).reshape(3, 3)
r = np.arange(9, 18).reshape(3, 3)
print(j)
print(r)
res = np.kron(j, r)
print("Произведение Кронекера из указанных массивов:")
print(res)

[1 3 9]
[2 1 0]
Произведение Кронекера из указанных массивов:
[ 2  1  0  6  3  0 18  9  0]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
Произведение Кронекера из указанных массивов:
[[  0   0   0   9  10  11  18  20  22]
 [  0   0   0  12  13  14  24  26  28]
 [  0   0   0  15  16  17  30  32  34]
 [ 27  30  33  36  40  44  45  50  55]
 [ 36  39  42  48  52  56  60  65  70]
 [ 45  48  51  60  64  68  75  80  85]
 [ 54  60  66  63  70  77  72  80  88]
 [ 72  78  84  84  91  98  96 104 112]
 [ 90  96 102 105 112 119 120 128 136]]


# 11. Напишите программу NumPy для вычисления определителя массива. 

In [22]:
import numpy as np
w = np.array([[1,34],[3,4]])
print(w)
res =  np.linalg.det(w)
print("Определитель указанного массива:")
print(res)

[[ 1 34]
 [ 3  4]]
Определитель указанного массива:
-98.00000000000004


# 17. Напишите программу NumPy, чтобы получить факторизацию qr для данного массива. 

In [24]:
import numpy as np
e = np.array([[32, 12, -45], [12, 21, -78], [-32, -90, 98]], dtype=np.int32)
print(e)
b, a = np.linalg.qr(e)
print("qr факторизация указанного массива:")
print( "b=\n", b, "\na=\n", a)

[[ 32  12 -45]
 [ 12  21 -78]
 [-32 -90  98]]
qr факторизация указанного массива:
b=
 [[-0.68348613  0.71267754 -0.15791593]
 [-0.2563073  -0.0317451   0.96607392]
 [ 0.68348613  0.70077313  0.20436179]] 
a=
 [[-46.81879964 -75.09803811 117.73048523]
 [  0.         -55.184098    39.08139503]
 [  0.           0.         -48.22009342]]


# 18. Напишите программу NumPy для вычисления коэффициента данного массива путем разложения по сингулярным значениям.


In [26]:
import numpy as np
k = np.array([[4, 0, 0, 0, 8], [0, 0, 9, 0, 0], [0, 0, 0, 0, 0], [0, 212, 0, 0, 0]], dtype=np.float32)
print(k)
l, a, q = np.linalg.svd(k, full_matrices=False)
g, u = np.linalg.qr(k)
print("Коэффициент заданного массива по сингулярному разложению:")
print("l=\n", l, "\na=\n", a, "\nq=\n", q)

[[  4.   0.   0.   0.   8.]
 [  0.   0.   9.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [  0. 212.   0.   0.   0.]]
Коэффициент заданного массива по сингулярному разложению:
l=
 [[ 0.  0.  1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0. -1.]
 [ 1.  0.  0.  0.]] 
a=
 [212.         9.         8.944272   0.      ] 
q=
 [[-0.         1.         0.         0.         0.       ]
 [-0.         0.         1.         0.         0.       ]
 [ 0.4472136  0.         0.         0.         0.8944272]
 [ 0.         0.         0.         1.         0.       ]]
